# Generated by Django 4.2.7 on 2025-11-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_ID', models.AutoField(db_column='Customer_ID', primary_key=True, serialize=False)),
                ('First_Name', models.CharField(db_column='First_Name', max_length=255)),
                ('Last_Name', models.CharField(db_column='Last_Name', max_length=255)),
                ('Mobile_No', models.CharField(db_column='Mobile_No', max_length=50, unique=True)),
                ('Password', models.CharField(db_column='Password', max_length=255)),
                ('Address', models.TextField(blank=True, db_column='Address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'CUSTOMER',
                'managed': False,
            },
        ),
    ]
